/**
 * Canonical role strings for talent onboarding fuzzy pick / type-ahead.
 * Creative, technical, media, marketing, and development — deduped, title case friendly.
 */
import { DEFAULT_ROLES } from "@/lib/roles";

const EXTRA_TALENT_ROLES = [
  // Creative & craft
  "Illustrator",
  "Graphic Designer",
  "UI Designer",
  "UX Designer",
  "UX Researcher",
  "Visual Designer",
  "Brand Strategist",
  "Creative Strategist",
  "Storyboard Artist",
  "Stylist",
  "Set Designer",
  "Lighting Technician",
  "Sound Designer",
  "Sound Engineer",
  "DIT / Media Manager",
  "Drone Operator",
  "Camera Operator",
  "Gaffer",
  "Scriptwriter",
  "Screenwriter",
  "Podcast Producer",
  "Radio Producer",
  "Broadcast Producer",
  "Livestream Director",
  "Virtual Production TD",
  "Compositor",
  "VFX Artist",
  "VFX Supervisor",
  "CG Generalist",
  "Game Designer",
  "Level Designer",
  "Character Designer",
  "Fashion Photographer",
  "Product Photographer",
  "Food Photographer",
  "Architectural Photographer",
  "Documentary Filmmaker",
  "Commercial Director",
  "Film Director",
  "Showrunner",
  "Casting Director",
  "Location Manager",
  "Production Designer",
  "Wardrobe Stylist",
  "Hair & Makeup Artist",
  "MUA / Makeup Artist",
  // Editorial & writing
  "Editorial Director",
  "Managing Editor",
  "Journalist",
  "Ghostwriter",
  "Technical Writer",
  "Subtitle / Localization Writer",
  "Arabic Copywriter",
  "Bilingual Copywriter",
  // Social & community
  "Community Manager",
  "Creator Manager",
  "Influencer Marketing Manager",
  "Social Analyst",
  "Paid Social Specialist",
  "Organic Social Lead",
  "TikTok Specialist",
  "YouTube Strategist",
  "LinkedIn Content Lead",
  // Marketing (non-creative-heavy)
  "Marketing Manager",
  "Brand Manager",
  "Product Marketing Manager",
  "Performance Marketer",
  "Growth Marketer",
  "CRM Manager",
  "Email Marketing Specialist",
  "SEO Specialist",
  "SEM / PPC Specialist",
  "Marketing Analyst",
  "Marketing Operations",
  "Demand Gen Manager",
  "Lifecycle Marketer",
  "Affiliate Manager",
  "Partnerships Manager",
  "Events Marketing",
  "Field Marketing",
  "Go-to-Market Lead",
  // Media & comms (non-technical)
  "Media Planner",
  "Media Strategist",
  "Communications Manager",
  "Public Affairs",
  "Corporate Communications",
  "Internal Communications",
  "Spokesperson / Host",
  "Moderator / MC",
  "Translator",
  "Interpreter",
  "Localization Manager",
  // Development & technical
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "Mobile Developer (iOS)",
  "Mobile Developer (Android)",
  "React Developer",
  "Next.js Developer",
  "Webflow Developer",
  "Shopify Developer",
  "WordPress Developer",
  "Unity Developer",
  "Unreal Developer",
  "Technical Artist",
  "Pipeline TD",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Data Engineer",
  "Data Analyst",
  "Machine Learning Engineer",
  "QA Engineer",
  "Solutions Architect",
  "Solutions Engineer",
  "Sales Engineer",
  "IT Support",
  "Network Engineer",
  "Cybersecurity Analyst",
  "Product Manager",
  "Technical Product Manager",
  "Scrum Master",
  "Business Analyst",
  // Audio / music extended
  "Composer",
  "Mixing Engineer",
  "Mastering Engineer",
  "Foley Artist",
  "ADR Recordist",
  // Strategy & ops
  "Operations Manager",
  "Program Manager",
  "Account Manager",
  "Client Services",
  "Executive Producer",
  "Line Producer",
  "Production Coordinator",
  "Post-Production Supervisor",
  "Freelance Generalist",
] as const;

function dedupeRoles(list: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const r of list) {
    const k = r.trim().toLowerCase();
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(r.trim());
  }
  return out.sort((a, b) => a.localeCompare(b));
}

export const TALENT_ROLE_CATALOG: string[] = dedupeRoles([
  ...DEFAULT_ROLES,
  ...Array.from(EXTRA_TALENT_ROLES),
]);
