import type { OnboardingStepDef } from "./types";

export const ONBOARDING_STEPS: OnboardingStepDef[] = [
  {
    id: "a_name",
    section: "A",
    prompt: "What's your name?",
    kind: "text",
    placeholder: "Full name",
    patchKeys: ["name"],
  },
  {
    id: "a_roles",
    section: "A",
    prompt: "What do you do? Pick everything that fits — we'll ask for your main focus next.",
    kind: "roles_multi",
    patchKeys: ["skills"],
  },
  {
    id: "a_primary_role",
    section: "A",
    prompt: "Which one is your main focus?",
    kind: "role_primary",
    patchKeys: ["primaryRole"],
  },
  {
    id: "a_location",
    section: "A",
    prompt: "Where are you based?",
    kind: "text",
    placeholder: "e.g. Dubai, UAE",
    patchKeys: ["location"],
  },
  {
    id: "a_handle",
    section: "A",
    prompt: "What's your main social handle?",
    kind: "text",
    placeholder: "@handle or URL",
    patchKeys: ["instagram"],
  },
  {
    id: "a_portfolio",
    section: "A",
    prompt: "Drop a portfolio or showreel link — helps you get better briefs.",
    kind: "text",
    placeholder: "https://…",
    optional: true,
    patchKeys: ["portfolioUrl"],
  },
  {
    id: "a_bio",
    section: "A",
    prompt: "In one line, what makes you different?",
    kind: "text",
    placeholder: "What should brands remember about you?",
    patchKeys: ["bio"],
  },
  {
    id: "a_years",
    section: "A",
    prompt: "How long have you been doing this kind of work?",
    kind: "single",
    options: [
      { id: "0-2", label: "0–2 years" },
      { id: "3-5", label: "3–5 years" },
      { id: "6-9", label: "6–9 years" },
      { id: "10+", label: "10+ years" },
    ],
    patchKeys: ["yearsExperienceBand"],
  },
  {
    id: "a_industries",
    section: "A",
    prompt: "Pick your top 5 industries — in order of experience (first = strongest). Search, tap to add, then drag to rank.",
    kind: "rank_industries",
    patchKeys: ["rankedIndustries"],
  },
  {
    id: "b_intro",
    section: "meta",
    prompt: "Nice — we have the essentials. Next, a few quick choices on how you like to work.",
    kind: "section_transition",
    patchKeys: [],
  },
  {
    id: "b_work_best",
    section: "B",
    prompt: "I work best when…",
    kind: "single",
    options: [
      { id: "clear_brief", label: "The brief is clear and I can take ownership", iconKey: "brief" },
      { id: "close_team", label: "I'm working closely with a team", iconKey: "team" },
      { id: "shape_evolution", label: "There's room to shape the work as it evolves", iconKey: "wand" },
      { id: "direction_set", label: "The direction is set and I can focus on execution", iconKey: "target" },
    ],
    patchKeys: ["howIWorkBest"],
  },
  {
    id: "b_work_more",
    section: "B",
    prompt: "The kind of work I want more of is…",
    kind: "single",
    options: [
      { id: "social", label: "Social content", iconKey: "megaphone" },
      { id: "campaigns", label: "Campaigns", iconKey: "sparkle" },
      { id: "story", label: "Brand storytelling", iconKey: "wand" },
      { id: "editorial", label: "Premium editorial work", iconKey: "camera" },
    ],
    patchKeys: ["preferredProjectTypes"],
  },
  {
    id: "b_pace",
    section: "B",
    prompt: "The pace that suits me best is…",
    kind: "single",
    options: [
      { id: "fast", label: "Fast turnaround", iconKey: "zap" },
      { id: "ongoing", label: "Ongoing monthly work", iconKey: "calendar" },
      { id: "campaign", label: "Campaign-based work", iconKey: "megaphone" },
      { id: "craft", label: "Fewer projects with more craft", iconKey: "camera" },
    ],
    patchKeys: ["preferredPace"],
  },
  {
    id: "b_feedback",
    section: "B",
    prompt: "When feedback comes in, I usually…",
    kind: "single",
    options: [
      { id: "quick", label: "Make changes quickly and keep moving", iconKey: "zap" },
      { id: "realign", label: "Step back and realign before changing too much", iconKey: "target" },
      { id: "suggest", label: "Suggest a better way to solve it", iconKey: "wand" },
      { id: "rounds", label: "Prefer clear feedback rounds from the start", iconKey: "brief" },
    ],
    patchKeys: ["feedbackStyle"],
  },
  {
    id: "b_suited",
    section: "B",
    prompt: "I'm best suited to…",
    kind: "single",
    options: [
      { id: "solo", label: "Working independently", iconKey: "target" },
      { id: "small", label: "Working with a small team", iconKey: "team" },
      { id: "production", label: "Being part of a bigger production", iconKey: "camera" },
      { id: "brand_team", label: "Working closely with a brand team", iconKey: "brief" },
    ],
    patchKeys: ["suitedTeamScale"],
  },
  {
    id: "b_open",
    section: "B",
    prompt: "I'm open to…",
    kind: "single",
    options: [
      { id: "remote", label: "Remote work", iconKey: "map" },
      { id: "onsite", label: "On-site work", iconKey: "team" },
      { id: "hybrid", label: "Hybrid", iconKey: "sparkle" },
      { id: "travel", label: "Travel if needed", iconKey: "zap" },
    ],
    patchKeys: ["workModeOpenness"],
  },
  {
    id: "b_availability",
    section: "B",
    prompt: "My availability is…",
    kind: "single",
    options: [
      { id: "freelance", label: "Freelance", iconKey: "sparkle" },
      { id: "project", label: "Project-based", iconKey: "brief" },
      { id: "part", label: "Part-time", iconKey: "calendar" },
      { id: "full", label: "Full-time", iconKey: "team" },
    ],
    patchKeys: ["availabilityType"],
  },
  {
    id: "c_intro",
    section: "meta",
    prompt: "Improve your match quality",
    kind: "section_transition",
    patchKeys: [],
  },
  {
    id: "c_brands",
    section: "C",
    prompt: "What kind of brands suit you best?",
    kind: "multi",
    options: [
      { id: "emerging", label: "Emerging brands" },
      { id: "established", label: "Established brands" },
      { id: "luxury", label: "Luxury brands" },
      { id: "founder", label: "Founder-led brands" },
      { id: "media", label: "Media / publisher brands" },
      { id: "agencies", label: "Agencies" },
    ],
    patchKeys: ["brandFitPreferences"],
  },
  {
    id: "c_client_values",
    section: "C",
    prompt: "What do clients value you most for?",
    kind: "multi",
    options: [
      { id: "speed", label: "Speed" },
      { id: "taste", label: "Taste" },
      { id: "reliability", label: "Reliability" },
      { id: "ideas", label: "Ideas" },
      { id: "polish", label: "Polish" },
      { id: "organisation", label: "Organisation" },
    ],
    patchKeys: ["clientValueStrengths"],
  },
  {
    id: "c_team",
    section: "C",
    prompt: "What kind of team setup brings out your best work?",
    kind: "single",
    options: [
      { id: "founder", label: "Direct with the founder", iconKey: "team" },
      { id: "internal", label: "With a small internal team", iconKey: "team" },
      { id: "agency", label: "Agency-side collaboration", iconKey: "brief" },
      { id: "crew", label: "Larger production crew", iconKey: "camera" },
      { id: "independent", label: "Mostly independent", iconKey: "target" },
    ],
    patchKeys: ["teamSetupPreference"],
  },
];

export function stepIndexById(id: string): number {
  return ONBOARDING_STEPS.findIndex((s) => s.id === id);
}
